name: CI/CD

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build-test-package:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build MSI installer
        run: |
          python setup_cx_freeze.py build
          python setup_cx_freeze.py bdist_msi

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MatlabHelper-msi
          path: dist/*.msi
